name: Metrics

on:
  # Schedule updates (once a day at 6 AM UTC)
  schedule:
    - cron: "0 6 * * *"
  # Manual trigger
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          user: tslime
          repo: tslime
          plugin_activities: yes
          plugin_activities_limit: 5
          plugin_activities_days: 30
          plugin_activities_sections: history, chart
          plugin_activities_recent: yes
          plugin_activities_charts: yes
          config_timezone: UTC
